### ISSUE TITLE
Bugs on 2.1.62Qt6-B1

### ISSUE THREAD

**Issue by DoctorToBeIn23** [ankipalace/Advanced-Card-Styles#10]
Version ⁨2.1.62 (bf05fae9)⁩
Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
MacBook Pro
13-inch, M1, 2020
macOS Ventura Version 13.2.1

As you can see the Image Style is contorted and I wasnt able to adjust it because of that.

![image](https://user-images.githubusercontent.com/60248099/232543472-49e69930-5b25-4f7f-834a-ec30131ba0e8.jpeg)

**Comment by DoctorToBeIn23** [comment]
Bug is still there on 2.1.64Qt6

**Comment by DoctorToBeIn23** [comment]
@abdnh

**Comment by abdnh** [comment]
Looks like it only occurs on macOS. Can you try this in a separate profile and let me know if it fixes it for you?
[advanced_card_styles.zip](https://github.com/AnKing-Memberships/Advanced-Card-Styles/files/11601653/advanced_card_styles.zip)

**Comment by DoctorToBeIn23** [comment]
![image](https://github.com/AnKing-Memberships/Advanced-Card-Styles/assets/60248099/8a8137db-a78d-43b4-99d6-e2da200258ef)
Perfect fixed!
