### ISSUE TITLE
Incompatibility with 2.1.17 beta

### ISSUE THREAD

**Issue by ghost** [ankipalace/Advanced-Card-Styles#2]
#### Problem description
Open Anki 2.1.17
Throws an error
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [X] I've restarted Anki to see if it helps
 - [X] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [X] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [X] I've tried to disable other add-ons to see if there are any interactions present
 - [X ] My issue disappears when I hold shift while starting Anki.
 - [X] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up
Anki 2.1.17 Beta 8

##### If you are using Anki 2.1
Anki 2.1.17 (f4fb7319) Python 3.8.0 Qt 5.14.0 PyQt 5.13.2
Platform: Windows 10
Flags: frz=True ao=True sv=2

Add-ons:

AMBOSS add-on
Extended Card Stats During Review (disabled)
Anki  Kindle  AnKindle (disabled)
Edit Field During Review (disabled)
TagSelectorV2 (disabled)
Directly review without going through overview page
Auto Markdown (disabled)
Speed Focus Mode auto-alert auto-reveal auto-fail
No Distractions Full Screen (disabled)
Browser Search Box Quick Insert Tag Deck Notetype
GoldenDict Add-On (disabled)
Incremental Reading (disabled)
Multi-field Batch Update
Color Confirmation (disabled)
Special Fields (disabled)
Search in formatted text in any fields
Chinese Support Redux (disabled)
AnkiDiscord - Discord integration for Anki (disabled)
  Advanced Review Bottom Bar   (disabled)
Postpone cards review (disabled)
Replay audio from editor (disabled)
Improve speed of change of note type
Pretzel Logic Retention Benchmarking
Convert Subdecks to Tag Hierarchy (disabled)
HoochiePapa Randomize New Queue (disabled)
ImageResizer (disabled)
Explain deletions (disabled)
Add Table
Showing time in browser (disabled)
Field History (disabled)
Dict2Anki (disabled)
Localize Media (disabled)
Cacher In The Rye Windows
Quick note and deck buttons Fork for 21
Korean Support (disabled)
Tag Entry Enhancements (disabled)
Image Occlusion Enhanced for Anki 21 alpha
Search and Replace Tags
A half-automatic Forvo Downloader (disabled)
load balancer (disabled)
Deck Stats
Simple Timer and Stopwatch for Anki 21 (disabled)
HoochieMama Randomize Rev Queue (disabled)
Symbols
Syntax Highlighting for Code (disabled)
Japanese Pitch Accent
Touch Wood Show New Cards Left Hint
GODMODE faster shortcuts and Cloze switching (disabled)
Copy2Clipboard (disabled)
Media Import (disabled)
Cardistry Dynamically Adjust New Cards (disabled)
More Decks Stats and Time Left (disabled)
OpenInExternalEditorRenameDuplicate for ImageAudioVideo (disabled)
Simplified Review GUI (disabled)
Control Audio Playback Pause Skip backwardsforwards Stop Audio (disabled)
Anki Accountability 2 (disabled)
Full Screen Toggle (disabled)
Bulk-Generate Japanese Vocab Frequency Ranking
Advanced Card Styles
Kitten Rewards Gamification (disabled)
Doublethink Disables Normalization
MIA Dictionary (disabled)
Content Injector (disabled)
Statistics for Note Types Card Types and Tags
Cloze Hide All
Search EDICT (disabled)
Add tags by shortcuts in Reviewer window one shortcut for one tag (disabled)
 Offline User Manual and Guides en es fr pl ru
Searching PDF Reading  Note-Taking in Add Dialog (disabled)
Incremental Reading 5 - Make Incremental Reading Great Again (disabled)
Backup Key (disabled)
Push Paradox Sibling Cardistry (disabled)
Rebuild All  Empty All for Anki 21
Browser MaximizeHide TableEditor (disabled)
Stats Overview Pie Graph with Distinct Learning and-or Relearning Sections
Large and Colorful Buttons (disabled)
Anki Excel Sync
Hierarchical Tags Addon 20  21 (disabled)
Zoom 21
HoochieBaby Queue Controller  Day-Lrn Q (disabled)
Update add-ons when Anki starts (disabled)
Export deck to HTML (disabled)
Advanced Copy Fields (disabled)
Redesign (disabled)
Study Logger
Ignore accents in browser search
Learning Step and Review Interval Retention
Fastbar another toolbar for Anki 21 beta (disabled)
Sanseido Definitions Python3 Anki21 (disabled)
Export cards selected in the Browser
Audio Files
Customize Sidebar (disabled)
Edit new note type without needing a full sync (disabled)
Visual Feedback Remake Gamification (disabled)
FULLEST SCREEN Hide All Toolbars in Reviewer
If a note has no more card warns instead of deleting it
Add a tag to notes with missing media
remove linebreaks  do word wrap fork for 21 (disabled)
Symbols As You Type
Night Mode T1 2117 compatible (disabled)
Papercards - export your flashcards to paper (disabled)
Japanese Definition Scraper from weblio Dictionary
AnkiConnect
Enhanced cloze 21
Advanced note editor Multi-column Frozen fields LaTeXs result in editor (disabled)
Anki Fanfare GamificationFeedback (disabled)
LPCG LyricsPoetry Cloze Generator (disabled)
Toggle Tags via ReviewerEditorBrowser Context Menu (disabled)
Load Balanced Scheduler
Progress Bar (disabled)
Alternative Dialog for ReMemorize Touch-Friendly (disabled)
Duplicate Selected Notes (disabled)
Bold the cloze v218
Distinct Cards Studied Today Statistic
AutoDefine - Automatically define vocabulary words with pronunciations and image (disabled)
Browser Card Info Bar
Media Internalizer
Highlight Search Results in the Browser (disabled)
Search from Editor for Anki 21 (disabled)
Japanese Example Sentences
Customize Keyboard Shortcuts (disabled)
Quick Colour Changing
Empty cards returns more usable informations (disabled)
SerenityNow (disabled)
Progress Graphs and Stats for Learned and Matured Cards
show new siblings in order  no same day spacingrandomization for new siblings
MIA Japanese (disabled)
Batch Editing
Mini Format Pack (disabled)
Quick tagging 21
Daijirin Dictionary Scraper (disabled)
Anki Welcome Screen (disabled)
Add Hyperlink (disabled)
ReMemorize Rescheduler with sibling and logging v030 (disabled)
Opening the same window multiple time (disabled)
Reviewer Context Menu Search (disabled)
Holdem Cardfield Preserves add card history
DrawingPad (disabled)
Edit Field During Review Cloze
Japanese Support
Pop-up Wikipedia Beta
Separate Learn and Relearn in the Answer Buttons graph 21
HTML Editor Tweaks v01 (disabled)
Pinyin on top of Hanzi (disabled)
Keep model of add cards (disabled)
Session Manager (disabled)
AwesomeTTS for Anki 21 updated (disabled)
Throughput Historical (disabled)
SMART SPACEBAR automatic ease scoring (disabled)
Ease Factor Histogram
Replay buttons on card
Improving change note type
Frozen Fields (disabled)
Removes Empty Note Types for 21
Improved Quizlet to Anki 21 Importer (disabled)
Fast cards reposition (disabled)
Batch Download Pictures From Google Images (disabled)
add-on window search bar
Blitzkrieg Advanced Browser Sidebar BETA4
Anki Killstreaks (disabled)
Vocabulous (disabled)
Stepwise Map Retrieval (disabled)
Japanese Pitch Accent Notes (disabled)
Mouse Wheel Review (disabled)
Pokemanki for both Anki 20 and 21 (disabled)
Numeric Keypad Remapping  ease bugs fixed
Syllabus - Anki Statistics and Export by Tag and Deck (disabled)
deck and card info sidebar during review
Answer Button Sounds
Deck name in title 21 (disabled)
Life Drain
Polar Connect - PDF and Incremental Reading with Anki Sync
More Overview Stats 21
Reset Custom Study Limit Increases
Free Weekend - or Any Other Day (disabled)
FULLER SCREEN Hide Toolbar in Reviewer (disabled)
Additional Card Fields - Fork for 21 (disabled)
Change subdecks configuration (disabled)
Small Potatoes Show learning step count in days (disabled)
copy note contents to new Add window from Browser Reviewer Add EditCurrent
Word Query (disabled)
3 add-ons merged quicker anki explain deletion explain database check (disabled)
Increase autosave frequency
Adding note and changing note type become quicker (disabled)
Throughput Monitor (disabled)
Echelon - Improved Hierarchical Tags for Anki 21 (disabled)
Browser TableEditor side-by-side horizontal split
Create Filtered Deck from the Browser
Web Browser - Search selection Import texts and images automatically
Show duplicates (disabled)
Advanced Browser
Enhance main window (disabled)
Slackers Delight PostponeDefer Button (disabled)
Chinese Prestudy (disabled)
Image Search (disabled)
Ze Add note id (disabled)
Kanji Grid (disabled)
Show number of results in browser (disabled)
True Retention by Card Maturity (disabled)
Editor Autocomplete
Japanese Pronunciation  Pitch Accent (disabled)
Incremental Reading (disabled)
Windows Text Rendering Fix (disabled)
Birl Reinforcement (disabled)
Correct Answers Graph (disabled)
PomodoroTimer
Blitzkrieg II - Advanced Browser Sidebar (disabled)
cloze_as_one-master (disabled)
cloze_overlapper
good_riddance
popup_dictionary (disabled)
Puppy Reinforcement (disabled)
Review Heatmap
Subtag Completer (disabled)
Night Mode

```


#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*


```python
Anki 2.1.17 (f4fb7319) Python 3.8.0 Qt 5.14.0 PyQt 5.13.2
Platform: Windows 10
Flags: frz=True ao=True sv=?

C:\Users\John Smith\AppData\Roaming\Anki2\addons21\1625103157\AdvancedStylerGui.py:110: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if 'max-width' in attributes and attributes['max-width'] is not 'none':
C:\Users\John Smith\AppData\Roaming\Anki2\addons21\1625103157\AdvancedStylerGui.py:120: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if 'margin' in attributes and attributes['margin'] is not 'none':
C:\Users\John Smith\AppData\Roaming\Anki2\addons21\1625103157\AdvancedStylerGui.py:129: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if 'word-wrap' in attributes and attributes['word-wrap'] is 'break-word':
C:\Users\John Smith\AppData\Roaming\Anki2\addons21\1625103157\AdvancedStylerGui.py:236: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if 'max-width' in attributes and attributes['max-width'] is not 'none':
C:\Users\John Smith\AppData\Roaming\Anki2\addons21\1625103157\AdvancedStylerGui.py:246: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if 'max-height' in attributes and attributes['max-height'] is not 'none':
C:\Users\John Smith\AppData\Roaming\Anki2\addons21\1625103157\AdvancedStylerGui.py:281: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if textField.text() is not '':
C:\Users\John Smith\AppData\Roaming\Anki2\addons21\1625103157\AdvancedStylerGui.py:370: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.window.fontComboBox.currentText() is not '':
C:\Users\John Smith\AppData\Roaming\Anki2\addons21\1625103157\AdvancedStylerGui.py:373: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.window.sizeSpinBox.value() is not 0:
C:\Users\John Smith\AppData\Roaming\Anki2\addons21\1625103157\AdvancedStylerGui.py:383: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.window.cardTextColor.text() is not '':
C:\Users\John Smith\AppData\Roaming\Anki2\addons21\1625103157\AdvancedStylerGui.py:385: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.window.cardBGColor.text() is not '':
C:\Users\John Smith\AppData\Roaming\Anki2\addons21\1625103157\AdvancedStylerGui.py:390: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.window.cardWidthPerectSpinBox.value() is not 0:
C:\Users\John Smith\AppData\Roaming\Anki2\addons21\1625103157\AdvancedStylerGui.py:393: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.window.cardWidthPixelSpinBox.value() is not 0:
C:\Users\John Smith\AppData\Roaming\Anki2\addons21\1625103157\AdvancedStylerGui.py:400: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.window.cardMarginCustom.text() is not '':
C:\Users\John Smith\AppData\Roaming\Anki2\addons21\1625103157\AdvancedStylerGui.py:423: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.window.clozeSizeSpinBox.value() is not 0:
C:\Users\John Smith\AppData\Roaming\Anki2\addons21\1625103157\AdvancedStylerGui.py:426: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.window.clozeTextColor.text() is not None and self.window.clozeTextColor.text() is not '':
C:\Users\John Smith\AppData\Roaming\Anki2\addons21\1625103157\AdvancedStylerGui.py:428: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.window.clozeBGColor.text() is not None and self.window.clozeBGColor.text() is not '':
C:\Users\John Smith\AppData\Roaming\Anki2\addons21\1625103157\AdvancedStylerGui.py:431: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if len(clozeDict) is not 0:
C:\Users\John Smith\AppData\Roaming\Anki2\addons21\1625103157\AdvancedStylerGui.py:450: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.window.extraSizeSpinBox.value() is not 0:
C:\Users\John Smith\AppData\Roaming\Anki2\addons21\1625103157\AdvancedStylerGui.py:453: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.window.extraTextColor.text() is not None and self.window.extraTextColor.text() is not '':
C:\Users\John Smith\AppData\Roaming\Anki2\addons21\1625103157\AdvancedStylerGui.py:455: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.window.extraBGColor.text() is not None and self.window.extraBGColor.text() is not '':
C:\Users\John Smith\AppData\Roaming\Anki2\addons21\1625103157\AdvancedStylerGui.py:459: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if len(extraDict) is not 0:
C:\Users\John Smith\AppData\Roaming\Anki2\addons21\1625103157\AdvancedStylerGui.py:480: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.window.imgWidthPerectSpinBox.value() is not 0:
C:\Users\John Smith\AppData\Roaming\Anki2\addons21\1625103157\AdvancedStylerGui.py:483: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.window.imgWidthPixelSpinBox.value() is not 0:
C:\Users\John Smith\AppData\Roaming\Anki2\addons21\1625103157\AdvancedStylerGui.py:488: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.window.imgHeightPerectSpinBox.value() is not 0:
C:\Users\John Smith\AppData\Roaming\Anki2\addons21\1625103157\AdvancedStylerGui.py:491: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.window.imgHeightPixelSpinBox.value() is not 0:
C:\Users\John Smith\AppData\Roaming\Anki2\addons21\1625103157\AdvancedStylerGui.py:495: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.window.imgBorderColor.text() is not None and self.window.imgBorderPixelSpinBox.value() is not 0:
C:\Users\John Smith\AppData\Roaming\Anki2\addons21\1625103157\AdvancedStylerGui.py:509: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if len(imgDict) is not 0:
C:\Users\John Smith\AppData\Roaming\Anki2\addons21\1625103157\AdvancedStylerGui.py:533: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.window.boldTextColor.text() is not '':
C:\Users\John Smith\AppData\Roaming\Anki2\addons21\1625103157\AdvancedStylerGui.py:556: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.window.italicsTextColor.text() is not '':
C:\Users\John Smith\AppData\Roaming\Anki2\addons21\1625103157\AdvancedStylerGui.py:575: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.window.underlinedTextColor.text() is not '':
C:\Users\John Smith\AppData\Roaming\Anki2\addons21\1625103157\AdvancedStylerGui.py:592: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.window.linksTextColor.text() is not '':
C:\Users\John Smith\AppData\Roaming\Anki2\addons21\1625103157\AdvancedStylerGui.py:667: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if duration is not 0:
C:\Users\John Smith\AppData\Roaming\Anki2\addons21\1625103157\AdvancedStylerGui.py:714: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if timerStartIndex is not -1:
C:\Users\John Smith\AppData\Roaming\Anki2\addons21\1625103157\myCssParser.py:65: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if len(newDict) is not 0:  # may cause things to disappear
C:\Users\John Smith\AppData\Roaming\Anki2\addons21\1625103157\CssProfile.py:75: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if len(a) is not 0:  # this is a failsafe to keep program running but can lead to disappearing stuff
C:\Users\John Smith\AppData\Roaming\Anki2\addons21\1625103157\ProfileManager.py:57: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if exportPath is not '':
C:\Users\John Smith\AppData\Roaming\Anki2\addons21\1625103157\ProfileManager.py:76: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if importPath is not '':
C:\Users\John Smith\AppData\Roaming\Anki2\addons21\1625103157\Buttons.py:42: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if profileComboBox.findText(currentProfile) is not -1:
```

**Comment by Forger125** [comment]
Just to update, this bug is also happening on the newest stable release 2.1.19

**Debug info:**
Anki 2.1.19 (3c8690ae) Python 3.8.1 Qt 5.14.0 PyQt 5.13.2
Platform: Linux
Flags: frz=True ao=True sv=?

```
/home/taylorconroy/.local/share/Anki2/addons21/1625103157/AdvancedStylerGui.py:110: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if 'max-width' in attributes and attributes['max-width'] is not 'none':
/home/taylorconroy/.local/share/Anki2/addons21/1625103157/AdvancedStylerGui.py:120: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if 'margin' in attributes and attributes['margin'] is not 'none':
/home/taylorconroy/.local/share/Anki2/addons21/1625103157/AdvancedStylerGui.py:129: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if 'word-wrap' in attributes and attributes['word-wrap'] is 'break-word':
/home/taylorconroy/.local/share/Anki2/addons21/1625103157/AdvancedStylerGui.py:236: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if 'max-width' in attributes and attributes['max-width'] is not 'none':
/home/taylorconroy/.local/share/Anki2/addons21/1625103157/AdvancedStylerGui.py:246: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if 'max-height' in attributes and attributes['max-height'] is not 'none':
/home/taylorconroy/.local/share/Anki2/addons21/1625103157/AdvancedStylerGui.py:281: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if textField.text() is not '':
/home/taylorconroy/.local/share/Anki2/addons21/1625103157/AdvancedStylerGui.py:370: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.window.fontComboBox.currentText() is not '':
/home/taylorconroy/.local/share/Anki2/addons21/1625103157/AdvancedStylerGui.py:373: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.window.sizeSpinBox.value() is not 0:
/home/taylorconroy/.local/share/Anki2/addons21/1625103157/AdvancedStylerGui.py:383: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.window.cardTextColor.text() is not '':
/home/taylorconroy/.local/share/Anki2/addons21/1625103157/AdvancedStylerGui.py:385: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.window.cardBGColor.text() is not '':
/home/taylorconroy/.local/share/Anki2/addons21/1625103157/AdvancedStylerGui.py:390: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.window.cardWidthPerectSpinBox.value() is not 0:
/home/taylorconroy/.local/share/Anki2/addons21/1625103157/AdvancedStylerGui.py:393: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.window.cardWidthPixelSpinBox.value() is not 0:
/home/taylorconroy/.local/share/Anki2/addons21/1625103157/AdvancedStylerGui.py:400: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.window.cardMarginCustom.text() is not '':
/home/taylorconroy/.local/share/Anki2/addons21/1625103157/AdvancedStylerGui.py:423: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.window.clozeSizeSpinBox.value() is not 0:
/home/taylorconroy/.local/share/Anki2/addons21/1625103157/AdvancedStylerGui.py:426: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.window.clozeTextColor.text() is not None and self.window.clozeTextColor.text() is not '':
/home/taylorconroy/.local/share/Anki2/addons21/1625103157/AdvancedStylerGui.py:428: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.window.clozeBGColor.text() is not None and self.window.clozeBGColor.text() is not '':
/home/taylorconroy/.local/share/Anki2/addons21/1625103157/AdvancedStylerGui.py:431: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if len(clozeDict) is not 0:
/home/taylorconroy/.local/share/Anki2/addons21/1625103157/AdvancedStylerGui.py:450: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.window.extraSizeSpinBox.value() is not 0:
/home/taylorconroy/.local/share/Anki2/addons21/1625103157/AdvancedStylerGui.py:453: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.window.extraTextColor.text() is not None and self.window.extraTextColor.text() is not '':
/home/taylorconroy/.local/share/Anki2/addons21/1625103157/AdvancedStylerGui.py:455: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.window.extraBGColor.text() is not None and self.window.extraBGColor.text() is not '':
/home/taylorconroy/.local/share/Anki2/addons21/1625103157/AdvancedStylerGui.py:459: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if len(extraDict) is not 0:
/home/taylorconroy/.local/share/Anki2/addons21/1625103157/AdvancedStylerGui.py:480: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.window.imgWidthPerectSpinBox.value() is not 0:
/home/taylorconroy/.local/share/Anki2/addons21/1625103157/AdvancedStylerGui.py:483: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.window.imgWidthPixelSpinBox.value() is not 0:
/home/taylorconroy/.local/share/Anki2/addons21/1625103157/AdvancedStylerGui.py:488: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.window.imgHeightPerectSpinBox.value() is not 0:
/home/taylorconroy/.local/share/Anki2/addons21/1625103157/AdvancedStylerGui.py:491: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.window.imgHeightPixelSpinBox.value() is not 0:
/home/taylorconroy/.local/share/Anki2/addons21/1625103157/AdvancedStylerGui.py:495: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.window.imgBorderColor.text() is not None and self.window.imgBorderPixelSpinBox.value() is not 0:
/home/taylorconroy/.local/share/Anki2/addons21/1625103157/AdvancedStylerGui.py:509: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if len(imgDict) is not 0:
/home/taylorconroy/.local/share/Anki2/addons21/1625103157/AdvancedStylerGui.py:533: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.window.boldTextColor.text() is not '':
/home/taylorconroy/.local/share/Anki2/addons21/1625103157/AdvancedStylerGui.py:556: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.window.italicsTextColor.text() is not '':
/home/taylorconroy/.local/share/Anki2/addons21/1625103157/AdvancedStylerGui.py:575: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.window.underlinedTextColor.text() is not '':
/home/taylorconroy/.local/share/Anki2/addons21/1625103157/AdvancedStylerGui.py:592: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.window.linksTextColor.text() is not '':
/home/taylorconroy/.local/share/Anki2/addons21/1625103157/AdvancedStylerGui.py:667: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if duration is not 0:
/home/taylorconroy/.local/share/Anki2/addons21/1625103157/AdvancedStylerGui.py:714: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if timerStartIndex is not -1:
/home/taylorconroy/.local/share/Anki2/addons21/1625103157/myCssParser.py:65: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if len(newDict) is not 0:  # may cause things to disappear
/home/taylorconroy/.local/share/Anki2/addons21/1625103157/CssProfile.py:75: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if len(a) is not 0:  # this is a failsafe to keep program running but can lead to disappearing stuff
/home/taylorconroy/.local/share/Anki2/addons21/1625103157/ProfileManager.py:57: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if exportPath is not '':
/home/taylorconroy/.local/share/Anki2/addons21/1625103157/ProfileManager.py:76: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if importPath is not '':
/home/taylorconroy/.local/share/Anki2/addons21/1625103157/Buttons.py:42: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if profileComboBox.findText(currentProfile) is not -1:
```

**Comment by AlienFever** [comment]
Hi thank you for submitting the issue.
Unfortunately my exams are soon and I can't afford to update anki and test it.
It seems though that if you open the .py files and change "is not" to "!=" it should fix the problem.

**Comment by ghost** [comment]
Thank you. 
That fixed the problem along with replacing 
if 'word-wrap' in attributes and attributes['word-wrap'] is 'break-word':
with
if 'word-wrap' in attributes and attributes['word-wrap'] == 'break-word':
in AdvancedStylerGui.py

**Comment by AlienFever** [comment]
Great !

**Comment by JhonatanDominici** [comment]
@Cupbox 
![2020-04-04 (2)](https://user-images.githubusercontent.com/63142191/78421506-89d72780-7658-11ea-842c-55ec801ccd3d.png)

How I fix this problem?

Thanks man
