### ISSUE TITLE
Anki throws error when attempt made to edit cards while studying

### ISSUE THREAD

**Issue by SEE-ICT** [ankipalace/Advanced-Card-Styles#3]
#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

1. I open a deck and click Study Now
2. In the Study window, I click Edit
3. In the Edit window, I click Cards...
4. Anki throws an error

If I close the error message window, I can edit cards, apparently without problems

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ x] I've restarted Anki to see if it helps
 - [ x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x ] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [ ] I've tried to disable other add-ons to see if there are any interactions present
 - [x ] My issue disappears when I hold shift while starting Anki.
 - [ x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please fill out the section corresponding with your Anki version:*

##### If you are using Anki 2.1

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.28 (7d8818f8) Python 3.8.0 Qt 5.15.0 PyQt 5.15.0
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-08-05 19:59:35

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 482, in handler
  File "aqt\editor.py", line 479, in <lambda>
  File "aqt\editor.py", line 357, in _onCardLayout
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-24>", line 2, in __init__
  File "lib\site-packages\anki\hooks.py", line 638, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 630, in repl
  File "D:\Program Data\Anki\addons21\1625103157\__init__.py", line 30, in afterInit
    buttons = Buttons(topCardLayout)
  File "D:\Program Data\Anki\addons21\1625103157\Buttons.py", line 21, in __init__
    self.initalizeUI()
  File "D:\Program Data\Anki\addons21\1625103157\Buttons.py", line 40, in initalizeUI
    currentProfile, _ = self.getCurrentProfileNameAndSaveStatus()
  File "D:\Program Data\Anki\addons21\1625103157\Buttons.py", line 242, in getCurrentProfileNameAndSaveStatus
    cssText = cssBox.toPlainText()
AttributeError: 'NoneType' object has no attribute 'toPlainText'
```

```

*Please fill in details about your operating system (Windows/macOS/Linux, which version):*

- OS: Windows
- version: 10

*Please open Anki, go to Tools → Add-ons, take a screenshot of your installed add-ons, and paste it below:*

![image](https://user-images.githubusercontent.com/32590442/89459027-515f6b80-d768-11ea-8b69-2adba45f1f50.png)


#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

See above

```python

```

**Comment by SEE-ICT** [comment]
Cloze_Hide_All has checked his code, and it's not the source of the problem. He suggests that Advanced_Card_Styles is where the issue lies: https://github.com/trgkanki/cloze_hide_all/issues/17 . Is there any more information that would be helpful to you in solving this problem?

**Comment by AlienFever** [comment]
Hey

Yes this addon in not compatible with the newer card editor in Anki.
I am afraid there is no easy fix for this one. I would have to redesign the way it integrates into Anki.
I'm sorry to say this but this addon is not being maintained anymore. Please delete it if it causes you problems.

Thank you for understanding.

**Comment by SEE-ICT** [comment]
Thanks for letting me know the situation. I'm sorry it would too much work to adapt to the new Anki, and thanks for having the initiative to create the add on in the first place.
